services:
  - type: web
    name: lawloom-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb://localhost:27017/lawDBmongodb+srv://lawloom-admin:Lawloom@2026@cluster0.5f7ol3x.mongodb.net/?appName=Cluster0
